# Geliştirme ortamına özel ayarlar
spring:
  datasource:
    url: jdbc:h2:file:./testdb-dev
    username: sa
    password: sa
  jpa:
    show-sql: true

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /sample-api/v3/api-docs
  swagger-ui:
    path: /sample-api/swagger-ui
    url: /sample-api/v3/api-docs
